import { Token } from "../../src/types";

export const testFiles: Array<{
    path: string;
    expectedTokens: Token[];
}> = [
    {
        expectedTokens: [
            { type: "Keyword", value: "interface" },
            { type: "Keyword", value: "Boblike" },
            { type: "BlockOpen" },
            { type: "Keyword", value: "name" },
            { type: "Colon" },
            { type: "Keyword", value: "String" },
            { type: "SemiColon" },
            { type: "Keyword", value: "shy" },
            { type: "Colon" },
            { type: "Keyword", value: "Bool" },
            { type: "SemiColon" },
            { type: "Keyword", value: "person" },
            { type: "QuestionMark" },
            { type: "Colon" },
            { type: "Keyword", value: "Bool" },
            { type: "SemiColon" },
            { type: "BlockClose" },
            { type: "Keyword", value: "match" },
            { type: "Slash" },
            { type: "Keyword", value: "bobs" },
            { type: "Slash" },
            { type: "IndexOpen" },
            { type: "Keyword", value: "bob" },
            { type: "IndexClose" },
            { type: "BlockOpen" },
            { type: "Keyword", value: "write" },
            { type: "Colon" },
            { type: "Keyword", value: "bob.name" },
            { type: "Equals" },
            { type: "Keyword", value: ",382" },
            { type: "SemiColon" },
            { type: "BlockClose" }
        ],
        path: "./test/testFiles/1.kakao"
    },
    {
        expectedTokens: [
            { type: "Keyword", value: "interface" },
            { type: "Keyword", value: "User" },
            { type: "BlockOpen" },
            { type: "Keyword", value: "name" },
            { type: "Colon" },
            { type: "Keyword", value: "String" },
            { type: "SemiColon" },
            { type: "Keyword", value: "displayName" },
            { type: "QuestionMark" },
            { type: "Colon" },
            { type: "Keyword", value: "String" },
            { type: "SemiColon" },
            { type: "BlockClose" },
            { type: "Keyword", value: "interface" },
            { type: "Keyword", value: "Resturant" },
            { type: "BlockOpen" },
            { type: "Keyword", value: "name" },
            { type: "Colon" },
            { type: "Keyword", value: "String" },
            { type: "SemiColon" },
            { type: "Keyword", value: "location" },
            { type: "Colon" },
            { type: "Keyword", value: "Geopoint" },
            { type: "SemiColon" },
            { type: "Keyword", value: "url" },
            { type: "QuestionMark" },
            { type: "Colon" },
            { type: "Keyword", value: "String" },
            { type: "SemiColon" },
            { type: "Keyword", value: "owner" },
            { type: "Colon" },
            { type: "Keyword", value: "String" },
            { type: "SemiColon" },
            { type: "BlockClose" },
            { type: "Keyword", value: "interface" },
            { type: "Keyword", value: "Review" },
            { type: "BlockOpen" },
            { type: "Keyword", value: "title" },
            { type: "Colon" },
            { type: "Keyword", value: "String" },
            { type: "SemiColon" },
            { type: "Keyword", value: "stars" },
            { type: "Colon" },
            { type: "Keyword", value: "Number" },
            { type: "SemiColon" },
            { type: "Keyword", value: "imageURL" },
            { type: "QuestionMark" },
            { type: "Colon" },
            { type: "Keyword", value: "String" },
            { type: "Or" },
            { type: "Keyword", value: "Number" },
            { type: "SemiColon" },
            { type: "Keyword", value: "user" },
            { type: "Colon" },
            { type: "Keyword", value: "String" },
            { type: "SemiColon" },
            { type: "BlockClose" },
            { type: "Keyword", value: "match" },
            { type: "Slash" },
            { type: "Keyword", value: "users" },
            { type: "Slash" },
            { type: "IndexOpen" },
            { type: "Keyword", value: "user" },
            { type: "IndexClose" },
            { type: "BlockOpen" },
            { type: "Keyword", value: "read" },
            { type: "Colon" },
            { type: "Keyword", value: "request.auth" },
            { type: "NotEquals" },
            { type: "Keyword", value: "null" },
            { type: "SemiColon" },
            { type: "Keyword", value: "write" },
            { type: "Colon" },
            { type: "BlockOpen" },
            { type: "Keyword", value: "if" },
            { type: "Keyword", value: "request.auth.uid" },
            { type: "Equals" },
            { type: "Keyword", value: "user.id" },
            { type: "BlockOpen" },
            { type: "Keyword", value: "return" },
            { type: "Keyword", value: "user" },
            { type: "Keyword", value: "isOnly" },
            { type: "Keyword", value: "User" },
            { type: "SemiColon" },
            { type: "BlockClose" },
            { type: "Keyword", value: "return" },
            { type: "Keyword", value: "false" },
            { type: "SemiColon" },
            { type: "BlockClose" },
            { type: "Comma" },
            { type: "BlockClose" },
            { type: "Keyword", value: "match" },
            { type: "Slash" },
            { type: "Keyword", value: "resturants" },
            { type: "Slash" },
            { type: "IndexOpen" },
            { type: "Keyword", value: "resturant" },
            { type: "IndexClose" },
            { type: "BlockOpen" },
            { type: "Keyword", value: "read" },
            { type: "Colon" },
            { type: "Keyword", value: "request.auth" },
            { type: "NotEquals" },
            { type: "Keyword", value: "null" },
            { type: "SemiColon" },
            { type: "Keyword", value: "create" },
            { type: "Colon" },
            { type: "BlockOpen" },
            { type: "Keyword", value: "if" },
            { type: "Keyword", value: "resturant" },
            { type: "Keyword", value: "isOnly" },
            { type: "Keyword", value: "Resturant" },
            { type: "BlockOpen" },
            { type: "Keyword", value: "return" },
            { type: "Keyword", value: "resturant.owner" },
            { type: "Equals" },
            { type: "Keyword", value: "request.auth.uid" },
            { type: "SemiColon" },
            { type: "BlockClose" },
            { type: "Keyword", value: "return" },
            { type: "Keyword", value: "false" },
            { type: "SemiColon" },
            { type: "BlockClose" },
            { type: "Comma" },
            { type: "Keyword", value: "write" },
            { type: "Colon" },
            { type: "BlockOpen" },
            { type: "Keyword", value: "if" },
            { type: "Keyword", value: "resource.owner" },
            { type: "Equals" },
            { type: "Keyword", value: "request.auth.uid" },
            { type: "BlockOpen" },
            { type: "Keyword", value: "return" },
            { type: "Keyword", value: "resturant" },
            { type: "Keyword", value: "isOnly" },
            { type: "Keyword", value: "Resturant" },
            { type: "SemiColon" },
            { type: "BlockClose" },
            { type: "Keyword", value: "return" },
            { type: "Keyword", value: "false" },
            { type: "SemiColon" },
            { type: "BlockClose" },
            { type: "Comma" },
            { type: "Keyword", value: "match" },
            { type: "Slash" },
            { type: "Keyword", value: "reviews" },
            { type: "Slash" },
            { type: "IndexOpen" },
            { type: "Keyword", value: "review" },
            { type: "IndexClose" },
            { type: "BlockOpen" },
            { type: "Keyword", value: "read" },
            { type: "Colon" },
            { type: "Keyword", value: "request.auth" },
            { type: "NotEquals" },
            { type: "Keyword", value: "null" },
            { type: "SemiColon" },
            { type: "Keyword", value: "create" },
            { type: "Colon" },
            { type: "BlockOpen" },
            { type: "Keyword", value: "if" },
            { type: "Keyword", value: "review" },
            { type: "Keyword", value: "isOnly" },
            { type: "Keyword", value: "Review" },
            { type: "BlockOpen" },
            { type: "Keyword", value: "return" },
            { type: "Keyword", value: "review.user" },
            { type: "Equals" },
            { type: "Keyword", value: "request.auth.uid" },
            { type: "SemiColon" },
            { type: "BlockClose" },
            { type: "Keyword", value: "return" },
            { type: "Keyword", value: "false" },
            { type: "SemiColon" },
            { type: "BlockClose" },
            { type: "Keyword", value: "delete" },
            { type: "Colon" },
            { type: "Keyword", value: "resource.user" },
            { type: "Equals" },
            { type: "Keyword", value: "request.auth.uid" },
            { type: "SemiColon" },
            { type: "BlockClose" },
            { type: "BlockClose" }
        ],
        path: "./test/testFiles/2.kakao"
    },
    {
        expectedTokens: [
            { type: "Keyword", value: "interface" },
            { type: "Keyword", value: "User" },
            { type: "BlockOpen" },
            { type: "Keyword", value: "displayName" },
            { type: "Colon" },
            { type: "Keyword", value: "String" },
            { type: "SemiColon" },
            { type: "BlockClose" },
            { type: "Keyword", value: "interface" },
            { type: "Keyword", value: "Chat" },
            { type: "BlockOpen" },
            { type: "Keyword", value: "title" },
            { type: "Colon" },
            { type: "Keyword", value: "String" },
            { type: "SemiColon" },
            { type: "Keyword", value: "creator" },
            { type: "Colon" },
            { type: "Keyword", value: "String" },
            { type: "SemiColon" },
            { type: "BlockClose" },
            { type: "Keyword", value: "interface" },
            { type: "Keyword", value: "Message" },
            { type: "BlockOpen" },
            { type: "Keyword", value: "content" },
            { type: "Colon" },
            { type: "Keyword", value: "String" },
            { type: "SemiColon" },
            { type: "Keyword", value: "sender" },
            { type: "Colon" },
            { type: "Keyword", value: "String" },
            { type: "SemiColon" },
            { type: "Keyword", value: "sendDate" },
            { type: "Colon" },
            { type: "Keyword", value: "Timestamp" },
            { type: "SemiColon" },
            { type: "BlockClose" },
            { type: "Keyword", value: "match" },
            { type: "Slash" },
            { type: "Keyword", value: "users" },
            { type: "Slash" },
            { type: "IndexOpen" },
            { type: "Keyword", value: "user" },
            { type: "IndexClose" },
            { type: "BlockOpen" },
            { type: "Keyword", value: "read" },
            { type: "Colon" },
            { type: "Keyword", value: "true" },
            { type: "SemiColon" },
            { type: "Keyword", value: "write" },
            { type: "Colon" },
            { type: "BlockOpen" },
            { type: "Keyword", value: "if" },
            { type: "Keyword", value: "user.id" },
            { type: "Equals" },
            { type: "Keyword", value: "request.auth.uid" },
            { type: "BlockOpen" },
            { type: "Keyword", value: "if" },
            { type: "Keyword", value: "user" },
            { type: "Keyword", value: "isOnly" },
            { type: "Keyword", value: "User" },
            { type: "BlockOpen" },
            { type: "Keyword", value: "return" },
            { type: "Keyword", value: "true" },
            { type: "SemiColon" },
            { type: "BlockClose" },
            { type: "Keyword", value: "return" },
            { type: "Keyword", value: "false" },
            { type: "SemiColon" },
            { type: "BlockClose" },
            { type: "Keyword", value: "return" },
            { type: "Keyword", value: "false" },
            { type: "SemiColon" },
            { type: "BlockClose" },
            { type: "BlockClose" },
            { type: "Keyword", value: "match" },
            { type: "Slash" },
            { type: "Keyword", value: "chats" },
            { type: "Slash" },
            { type: "IndexOpen" },
            { type: "Keyword", value: "chat" },
            { type: "IndexClose" },
            { type: "BlockOpen" },
            { type: "Keyword", value: "read" },
            { type: "Colon" },
            { type: "Keyword", value: "true" },
            { type: "SemiColon" },
            { type: "Keyword", value: "create" },
            { type: "Colon" },
            { type: "BlockOpen" },
            { type: "Keyword", value: "if" },
            { type: "Keyword", value: "chat.creator" },
            { type: "Equals" },
            { type: "Keyword", value: "request.auth.uid" },
            { type: "BlockOpen" },
            { type: "Keyword", value: "return" },
            { type: "Keyword", value: "chat" },
            { type: "Keyword", value: "isOnly" },
            { type: "Keyword", value: "Chat" },
            { type: "SemiColon" },
            { type: "BlockClose" },
            { type: "Keyword", value: "return" },
            { type: "Keyword", value: "false" },
            { type: "SemiColon" },
            { type: "BlockClose" },
            { type: "Comma" },
            { type: "Keyword", value: "match" },
            { type: "Slash" },
            { type: "Keyword", value: "messages" },
            { type: "Slash" },
            { type: "IndexOpen" },
            { type: "Keyword", value: "message" },
            { type: "IndexClose" },
            { type: "BlockOpen" },
            { type: "Keyword", value: "read" },
            { type: "Colon" },
            { type: "Keyword", value: "true" },
            { type: "SemiColon" },
            { type: "Keyword", value: "create" },
            { type: "Colon" },
            { type: "BlockOpen" },
            { type: "Keyword", value: "if" },
            { type: "Keyword", value: "message.sender" },
            { type: "Equals" },
            { type: "Keyword", value: "request.auth.uid" },
            { type: "BlockOpen" },
            { type: "Keyword", value: "return" },
            { type: "Keyword", value: "message" },
            { type: "Keyword", value: "isOnly" },
            { type: "Keyword", value: "Message" },
            { type: "SemiColon" },
            { type: "BlockClose" },
            { type: "Keyword", value: "return" },
            { type: "Keyword", value: "false" },
            { type: "SemiColon" },
            { type: "BlockClose" },
            { type: "BlockClose" },
            { type: "BlockClose" }
        ],
        path: "./test/testFiles/3.kakao"
    }
];
